//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_3cdxgppx {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_3cdxgppx() {
        }
        
        static object Create_ASP_pages_fs_fs300230_aspx() {
            return new ASP.pages_fs_fs300230_aspx();
        }
        
        static object Create_ASP_pages_fs_fs200600_aspx() {
            return new ASP.pages_fs_fs200600_aspx();
        }
        
        static object Create_ASP_pages_fs_fs204900_aspx() {
            return new ASP.pages_fs_fs204900_aspx();
        }
        
        static object Create_ASP_pages_fs_fs500100_aspx() {
            return new ASP.pages_fs_fs500100_aspx();
        }
        
        static object Create_ASP_pages_fs_fs305900_aspx() {
            return new ASP.pages_fs_fs305900_aspx();
        }
        
        static object Create_ASP_pages_fs_fs300210_aspx() {
            return new ASP.pages_fs_fs300210_aspx();
        }
        
        static object Create_ASP_pages_fs_fs100400_aspx() {
            return new ASP.pages_fs_fs100400_aspx();
        }
        
        static object Create_ASP_pages_fs_fs204400_aspx() {
            return new ASP.pages_fs_fs204400_aspx();
        }
    }
}
