//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_fxemfxix {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_fxemfxix() {
        }
        
        static object Create_ASP_pages_pm_pm404000_aspx() {
            return new ASP.pages_pm_pm404000_aspx();
        }
        
        static object Create_ASP_pages_pm_pm207000_aspx() {
            return new ASP.pages_pm_pm207000_aspx();
        }
        
        static object Create_ASP_pages_pm_pm209100_aspx() {
            return new ASP.pages_pm_pm209100_aspx();
        }
        
        static object Create_ASP_pages_pm_pm201000_aspx() {
            return new ASP.pages_pm_pm201000_aspx();
        }
        
        static object Create_ASP_pages_pm_pm101000_aspx() {
            return new ASP.pages_pm_pm101000_aspx();
        }
        
        static object Create_ASP_pages_pm_pm204100_aspx() {
            return new ASP.pages_pm_pm204100_aspx();
        }
        
        static object Create_ASP_pages_pm_pm208030_aspx() {
            return new ASP.pages_pm_pm208030_aspx();
        }
    }
}
