//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_oobf3kfi {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_oobf3kfi() {
        }
        
        static object Create_ASP_pages_fs_fs500201_aspx() {
            return new ASP.pages_fs_fs500201_aspx();
        }
        
        static object Create_ASP_pages_fs_fs501400_aspx() {
            return new ASP.pages_fs_fs501400_aspx();
        }
        
        static object Create_ASP_pages_fs_fs306100_aspx() {
            return new ASP.pages_fs_fs306100_aspx();
        }
        
        static object Create_ASP_pages_fs_fs100100_aspx() {
            return new ASP.pages_fs_fs100100_aspx();
        }
        
        static object Create_ASP_pages_fs_fs500400_aspx() {
            return new ASP.pages_fs_fs500400_aspx();
        }
        
        static object Create_ASP_pages_fs_fs201200_aspx() {
            return new ASP.pages_fs_fs201200_aspx();
        }
    }
}
