//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_bias1ylm {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_bias1ylm() {
        }
        
        static object Create_ASP_pages_pr_pr501000_aspx() {
            return new ASP.pages_pr_pr501000_aspx();
        }
        
        static object Create_ASP_pages_pr_pr204000_aspx() {
            return new ASP.pages_pr_pr204000_aspx();
        }
        
        static object Create_ASP_pages_pr_pr207000_aspx() {
            return new ASP.pages_pr_pr207000_aspx();
        }
        
        static object Create_ASP_pages_pr_pr209800_aspx() {
            return new ASP.pages_pr_pr209800_aspx();
        }
        
        static object Create_ASP_pages_pr_pr101040_aspx() {
            return new ASP.pages_pr_pr101040_aspx();
        }
        
        static object Create_ASP_pages_pr_pr209900_aspx() {
            return new ASP.pages_pr_pr209900_aspx();
        }
        
        static object Create_ASP_pages_pr_pr201000_aspx() {
            return new ASP.pages_pr_pr201000_aspx();
        }
        
        static object Create_ASP_pages_pr_pr205000_aspx() {
            return new ASP.pages_pr_pr205000_aspx();
        }
    }
}
