//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_wpd5knys {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_wpd5knys() {
        }
        
        static object Create_ASP_pages_in_in505000_aspx() {
            return new ASP.pages_in_in505000_aspx();
        }
        
        static object Create_ASP_pages_in_in208600_aspx() {
            return new ASP.pages_in_in208600_aspx();
        }
        
        static object Create_ASP_pages_in_in204010_aspx() {
            return new ASP.pages_in_in204010_aspx();
        }
        
        static object Create_ASP_pages_in_in103000_aspx() {
            return new ASP.pages_in_in103000_aspx();
        }
        
        static object Create_ASP_pages_in_in504000_aspx() {
            return new ASP.pages_in_in504000_aspx();
        }
        
        static object Create_ASP_pages_in_in407000_aspx() {
            return new ASP.pages_in_in407000_aspx();
        }
        
        static object Create_ASP_pages_in_in206000_aspx() {
            return new ASP.pages_in_in206000_aspx();
        }
    }
}
