#pragma checksum "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "162DE17421BFD8924FC547E6A4482D4849BD3515"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Page_RS202000 : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
    protected global::PX.Web.UI.PXDataSource ds;
    
    #line default
    #line hidden
    
    
    #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
    protected global::PX.Web.UI.PXFormView form;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
    
    public new ASP.masterpages_formview_master Master {
        get {
            return ((ASP.masterpages_formview_master)(base.Master));
        }
    }
}
namespace ASP {
    
    #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 4 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
    using System.Web.UI.DataVisualization.Charting;
    
    #line default
    #line hidden
    
    #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
    using PX.Web.UI;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class cstdesigner_admin_phonerepairshop_rs202000_aspx : global::Page_RS202000, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.cstdesigner_admin_phonerepairshop_rs202000_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public cstdesigner_admin_phonerepairshop_rs202000_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\RS202000.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/CstDesigner/admin_PhoneRepairShop/rs202000.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.cstdesigner_admin_phonerepairshop_rs202000_aspx.@__initialized == false)) {
                dependencies = new string[8];
                dependencies[0] = "~/CstDesigner/admin_PhoneRepairShop/rs202000.aspx";
                dependencies[1] = "~/Controls/PageTitle.ascx";
                dependencies[2] = "~/Controls/PageTitle.ascx.cs";
                dependencies[3] = "~/MasterPages/ListView.master";
                dependencies[4] = "~/MasterPages/ListView.master.cs";
                dependencies[5] = "~/CstDesigner/admin_PhoneRepairShop/RS202000.aspx.cs";
                dependencies[6] = "~/MasterPages/FormView.master";
                dependencies[7] = "~/MasterPages/FormView.master.cs";
                global::ASP.cstdesigner_admin_phonerepairshop_rs202000_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.cstdesigner_admin_phonerepairshop_rs202000_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        334,
                        3,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.cstdesigner_admin_phonerepairshop_rs202000_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.cstdesigner_admin_phonerepairshop_rs202000_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDataSource @__BuildControlds() {
            global::PX.Web.UI.PXDataSource @__ctrl;
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl = new global::PX.Web.UI.PXDataSource();
            
            #line default
            #line hidden
            this.ds = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.ID = "ds";
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.Visible = true;
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.TypeName = "PhoneRepairShop.RSSVDeviceMaint";
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.PrimaryView = "ServDevices";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        337,
                        206,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        543,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlcont1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDataSource @__ctrl2;
            
            #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl2 = this.@__BuildControlds();
            
            #line default
            #line hidden
            
            #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl3 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        627,
                        3,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        763,
                        3,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        868,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXLayoutRule @__BuildControl__control7() {
            global::PX.Web.UI.PXLayoutRule @__ctrl;
            
            #line 17 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl = new global::PX.Web.UI.PXLayoutRule();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            
            #line 17 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.ID = "PXLayoutRule1";
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.StartRow = true;
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.ControlSize = "M";
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.LabelsWidth = "S";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 17 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl1 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 17 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        766,
                        122,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n     ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        888,
                        7,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXSelector @__BuildControl__control10() {
            global::PX.Web.UI.PXSelector @__ctrl;
            
            #line 21 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl = new global::PX.Web.UI.PXSelector();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 21 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.ID = "DeviceCD";
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.DataField = "DeviceCD";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        895,
                        83,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        978,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXTextEdit @__BuildControl__control12() {
            global::PX.Web.UI.PXTextEdit @__ctrl;
            
            #line 23 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl = new global::PX.Web.UI.PXTextEdit();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 23 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.ID = "Description";
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.DataField = "Description";
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.DefaultLocale = "";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        980,
                        108,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1088,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXCheckBox @__BuildControl__control14() {
            global::PX.Web.UI.PXCheckBox @__ctrl;
            
            #line 26 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl = new global::PX.Web.UI.PXCheckBox();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 26 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.ID = "Active";
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.DataField = "Active";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1090,
                        79,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1169,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control17() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1276,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXLayoutRule @__BuildControl__control16() {
            global::PX.Web.UI.PXLayoutRule @__ctrl;
            
            #line 28 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl = new global::PX.Web.UI.PXLayoutRule();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            
            #line 28 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.ID = "PXLayoutRule2";
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.StartColumn = true;
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.ControlSize = "M";
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.LabelsWidth = "S";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 28 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl1 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 28 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1171,
                        125,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1296,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXCheckBox @__BuildControl__control19() {
            global::PX.Web.UI.PXCheckBox @__ctrl;
            
            #line 32 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl = new global::PX.Web.UI.PXCheckBox();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 32 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.ID = "PXCheckBox1";
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.DataField = "Active";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1298,
                        84,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control20() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1382,
                        3,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control5(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl1 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXLayoutRule @__ctrl2;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl2 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl3 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXSelector @__ctrl4;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl4 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl5 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXTextEdit @__ctrl6;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl6 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl7 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXCheckBox @__ctrl8;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl8 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl9 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXLayoutRule @__ctrl10;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl10 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl11 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXCheckBox @__ctrl12;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl12 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl13 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control21(PX.Web.UI.PXAutoSizeInfo @__ctrl) {
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.Container = global::PX.Web.UI.DockContainer.Window;
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.Enabled = true;
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.MinHeight = 200;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXFormView @__BuildControlform() {
            global::PX.Web.UI.PXFormView @__ctrl;
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl = new global::PX.Web.UI.PXFormView();
            
            #line default
            #line hidden
            this.form = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.Template = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control5), null);
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.ID = "form";
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.DataSourceID = "ds";
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.DataMember = "ServDevices";
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.AllowAutoHide = false;
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            this.@__BuildControl__control21(@__ctrl.AutoSize);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        630,
                        850,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control22() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1480,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlcont2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 13 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 13 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXFormView @__ctrl2;
            
            #line 13 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl2 = this.@__BuildControlform();
            
            #line default
            #line hidden
            
            #line 13 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 13 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl3 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 13 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(cstdesigner_admin_phonerepairshop_rs202000_aspx @__ctrl) {
            
            #line 1 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.MasterPageFile = "~/MasterPages/ListView.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__ctrl.Title = "Untitled Page";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            this.AddContentTemplate("phDS", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlcont1)));
            
            #line default
            #line hidden
            
            #line 13 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            this.AddContentTemplate("phL", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlcont2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\rs202000.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\CstDesigner\admin_PhoneRepairShop\RS202000.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            this.StyleSheetTheme = "Default";
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.cstdesigner_admin_phonerepairshop_rs202000_aspx.@__fileDependencies);
            this.ValidateRequestMode = System.Web.UI.ValidateRequestMode.Disabled;
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -368081814;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
