//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_4dmfwynx {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_4dmfwynx() {
        }
        
        static object Create_ASP_pages_sm_sm206036_aspx() {
            return new ASP.pages_sm_sm206036_aspx();
        }
        
        static object Create_ASP_pages_sm_sm502000_aspx() {
            return new ASP.pages_sm_sm502000_aspx();
        }
        
        static object Create_ASP_pages_sm_sm201040_aspx() {
            return new ASP.pages_sm_sm201040_aspx();
        }
        
        static object Create_ASP_pages_sm_sm200535_aspx() {
            return new ASP.pages_sm_sm200535_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204550_aspx() {
            return new ASP.pages_sm_sm204550_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204004_aspx() {
            return new ASP.pages_sm_sm204004_aspx();
        }
        
        static object Create_ASP_pages_sm_sm202010_aspx() {
            return new ASP.pages_sm_sm202010_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204530_aspx() {
            return new ASP.pages_sm_sm204530_aspx();
        }
    }
}
