//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_ylvy4xep {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_ylvy4xep() {
        }
        
        static object Create_ASP_pages_cr_cr503021_aspx() {
            return new ASP.pages_cr_cr503021_aspx();
        }
        
        static object Create_ASP_pages_cr_co409090_aspx() {
            return new ASP.pages_cr_co409090_aspx();
        }
        
        static object Create_ASP_pages_cr_co409080_aspx() {
            return new ASP.pages_cr_co409080_aspx();
        }
        
        static object Create_ASP_pages_cr_cr503010_aspx() {
            return new ASP.pages_cr_cr503010_aspx();
        }
        
        static object Create_ASP_pages_cr_co409030_aspx() {
            return new ASP.pages_cr_co409030_aspx();
        }
        
        static object Create_ASP_pages_cr_cr503120_aspx() {
            return new ASP.pages_cr_cr503120_aspx();
        }
        
        static object Create_ASP_pages_cr_cr503020_aspx() {
            return new ASP.pages_cr_cr503020_aspx();
        }
        
        static object Create_ASP_pages_cr_cr304500_aspx() {
            return new ASP.pages_cr_cr304500_aspx();
        }
    }
}
