//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_eypwuwig {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_eypwuwig() {
        }
        
        static object Create_ASP_pages_ep_ep204070_aspx() {
            return new ASP.pages_ep_ep204070_aspx();
        }
        
        static object Create_ASP_pages_ep_ep507030_aspx() {
            return new ASP.pages_ep_ep507030_aspx();
        }
        
        static object Create_ASP_pages_ep_ep502000_aspx() {
            return new ASP.pages_ep_ep502000_aspx();
        }
        
        static object Create_ASP_pages_ep_ep101000_aspx() {
            return new ASP.pages_ep_ep101000_aspx();
        }
        
        static object Create_ASP_pages_ep_ep404300_aspx() {
            return new ASP.pages_ep_ep404300_aspx();
        }
        
        static object Create_ASP_pages_ep_ep301000_aspx() {
            return new ASP.pages_ep_ep301000_aspx();
        }
    }
}
