//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_ilbxercz {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_ilbxercz() {
        }
        
        static object Create_ASP_pages_cs_cs204000_aspx() {
            return new ASP.pages_cs_cs204000_aspx();
        }
        
        static object Create_ASP_pages_cs_cs208500_aspx() {
            return new ASP.pages_cs_cs208500_aspx();
        }
        
        static object Create_ASP_pages_cs_cs209020_aspx() {
            return new ASP.pages_cs_cs209020_aspx();
        }
        
        static object Create_ASP_pages_cs_cs203100_aspx() {
            return new ASP.pages_cs_cs203100_aspx();
        }
        
        static object Create_ASP_pages_cs_cs212000_aspx() {
            return new ASP.pages_cs_cs212000_aspx();
        }
        
        static object Create_ASP_pages_cs_cs207035_aspx() {
            return new ASP.pages_cs_cs207035_aspx();
        }
        
        static object Create_ASP_pages_cs_cs210000_aspx() {
            return new ASP.pages_cs_cs210000_aspx();
        }
        
        static object Create_ASP_pages_cs_cs101000_aspx() {
            return new ASP.pages_cs_cs101000_aspx();
        }
    }
}
