//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_qz3vr5qm {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_qz3vr5qm() {
        }
        
        static object Create_ASP_pages_ar_ar522000_aspx() {
            return new ASP.pages_ar_ar522000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar507000_aspx() {
            return new ASP.pages_ar_ar507000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar409030_aspx() {
            return new ASP.pages_ar_ar409030_aspx();
        }
        
        static object Create_ASP_pages_ar_ar509900_aspx() {
            return new ASP.pages_ar_ar509900_aspx();
        }
        
        static object Create_ASP_pages_ar_ar512000_aspx() {
            return new ASP.pages_ar_ar512000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar510000_aspx() {
            return new ASP.pages_ar_ar510000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar506000_aspx() {
            return new ASP.pages_ar_ar506000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar304000_aspx() {
            return new ASP.pages_ar_ar304000_aspx();
        }
    }
}
