//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_c11l3s0h {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_c11l3s0h() {
        }
        
        static object Create_ASP_pages_pr_pr204000_aspx() {
            return new ASP.pages_pr_pr204000_aspx();
        }
        
        static object Create_ASP_pages_pr_pr201000_aspx() {
            return new ASP.pages_pr_pr201000_aspx();
        }
        
        static object Create_ASP_pages_pr_pr205000_aspx() {
            return new ASP.pages_pr_pr205000_aspx();
        }
        
        static object Create_ASP_pages_pr_pr102000_aspx() {
            return new ASP.pages_pr_pr102000_aspx();
        }
        
        static object Create_ASP_pages_pr_pr209700_aspx() {
            return new ASP.pages_pr_pr209700_aspx();
        }
        
        static object Create_ASP_pages_pr_pr101060_aspx() {
            return new ASP.pages_pr_pr101060_aspx();
        }
        
        static object Create_ASP_pages_pr_pr504000_aspx() {
            return new ASP.pages_pr_pr504000_aspx();
        }
        
        static object Create_ASP_pages_pr_pr505000_aspx() {
            return new ASP.pages_pr_pr505000_aspx();
        }
    }
}
