//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_02xnea3p {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_02xnea3p() {
        }
        
        static object Create_ASP_pages_sm_sm207040_aspx() {
            return new ASP.pages_sm_sm207040_aspx();
        }
        
        static object Create_ASP_pages_sm_sm203030_aspx() {
            return new ASP.pages_sm_sm203030_aspx();
        }
        
        static object Create_ASP_pages_sm_sm205520_aspx() {
            return new ASP.pages_sm_sm205520_aspx();
        }
        
        static object Create_ASP_pages_sm_sm201020_aspx() {
            return new ASP.pages_sm_sm201020_aspx();
        }
        
        static object Create_ASP_pages_sm_sm201005_aspx() {
            return new ASP.pages_sm_sm201005_aspx();
        }
        
        static object Create_ASP_pages_sm_sm206506_aspx() {
            return new ASP.pages_sm_sm206506_aspx();
        }
        
        static object Create_ASP_pages_sm_sm205080_aspx() {
            return new ASP.pages_sm_sm205080_aspx();
        }
        
        static object Create_ASP_pages_sm_sm604000_aspx() {
            return new ASP.pages_sm_sm604000_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204520_aspx() {
            return new ASP.pages_sm_sm204520_aspx();
        }
    }
}
