//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_1urmt10r {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_1urmt10r() {
        }
        
        static object Create_ASP_pages_in_in304000_aspx() {
            return new ASP.pages_in_in304000_aspx();
        }
        
        static object Create_ASP_pages_in_in103020_aspx() {
            return new ASP.pages_in_in103020_aspx();
        }
        
        static object Create_ASP_pages_in_in403000_aspx() {
            return new ASP.pages_in_in403000_aspx();
        }
        
        static object Create_ASP_pages_in_in103010_aspx() {
            return new ASP.pages_in_in103010_aspx();
        }
        
        static object Create_ASP_pages_in_in509000_aspx() {
            return new ASP.pages_in_in509000_aspx();
        }
        
        static object Create_ASP_pages_in_in202520_aspx() {
            return new ASP.pages_in_in202520_aspx();
        }
    }
}
