//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_2od3ac2p {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_2od3ac2p() {
        }
        
        static object Create_ASP_pages_sm_sm209500_aspx() {
            return new ASP.pages_sm_sm209500_aspx();
        }
        
        static object Create_ASP_pages_sm_sm209020_aspx() {
            return new ASP.pages_sm_sm209020_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204001_aspx() {
            return new ASP.pages_sm_sm204001_aspx();
        }
        
        static object Create_ASP_pages_sm_sm303010_aspx() {
            return new ASP.pages_sm_sm303010_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204580_aspx() {
            return new ASP.pages_sm_sm204580_aspx();
        }
        
        static object Create_ASP_pages_sm_sm200540_aspx() {
            return new ASP.pages_sm_sm200540_aspx();
        }
        
        static object Create_ASP_pages_sm_sm202030_aspx() {
            return new ASP.pages_sm_sm202030_aspx();
        }
        
        static object Create_ASP_pages_sm_sm202025_aspx() {
            return new ASP.pages_sm_sm202025_aspx();
        }
        
        static object Create_ASP_pages_sm_sm200550_aspx() {
            return new ASP.pages_sm_sm200550_aspx();
        }
    }
}
