//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_me5xvlkr {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_me5xvlkr() {
        }
        
        static object Create_ASP_pages_ar_ar504000_aspx() {
            return new ASP.pages_ar_ar504000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar501000_aspx() {
            return new ASP.pages_ar_ar501000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar409010_aspx() {
            return new ASP.pages_ar_ar409010_aspx();
        }
        
        static object Create_ASP_pages_ar_ar401000_aspx() {
            return new ASP.pages_ar_ar401000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar407000_aspx() {
            return new ASP.pages_ar_ar407000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar509000_aspx() {
            return new ASP.pages_ar_ar509000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar202800_aspx() {
            return new ASP.pages_ar_ar202800_aspx();
        }
        
        static object Create_ASP_pages_ar_ar404000_aspx() {
            return new ASP.pages_ar_ar404000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar521000_aspx() {
            return new ASP.pages_ar_ar521000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar102010_aspx() {
            return new ASP.pages_ar_ar102010_aspx();
        }
    }
}
