//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_sgmxraoo {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_sgmxraoo() {
        }
        
        static object Create_ASP_pages_sm_sm200529_aspx() {
            return new ASP.pages_sm_sm200529_aspx();
        }
        
        static object Create_ASP_pages_sm_sm200530_aspx() {
            return new ASP.pages_sm_sm200530_aspx();
        }
        
        static object Create_ASP_pages_sm_sm206035_aspx() {
            return new ASP.pages_sm_sm206035_aspx();
        }
        
        static object Create_ASP_pages_sm_sm205030_aspx() {
            return new ASP.pages_sm_sm205030_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204015_aspx() {
            return new ASP.pages_sm_sm204015_aspx();
        }
        
        static object Create_ASP_pages_sm_sm200522_aspx() {
            return new ASP.pages_sm_sm200522_aspx();
        }
        
        static object Create_ASP_pages_sm_sm201510_aspx() {
            return new ASP.pages_sm_sm201510_aspx();
        }
        
        static object Create_ASP_pages_sm_sm203510_aspx() {
            return new ASP.pages_sm_sm203510_aspx();
        }
    }
}
