//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_luf5b1pw {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_luf5b1pw() {
        }
        
        static object Create_ASP_pages_ep_ep208000_aspx() {
            return new ASP.pages_ep_ep208000_aspx();
        }
        
        static object Create_ASP_pages_ep_ep505020_aspx() {
            return new ASP.pages_ep_ep505020_aspx();
        }
        
        static object Create_ASP_pages_ep_ep503010_aspx() {
            return new ASP.pages_ep_ep503010_aspx();
        }
        
        static object Create_ASP_pages_ep_ep204040_aspx() {
            return new ASP.pages_ep_ep204040_aspx();
        }
        
        static object Create_ASP_pages_ep_ep507020_aspx() {
            return new ASP.pages_ep_ep507020_aspx();
        }
        
        static object Create_ASP_pages_ep_ep301030_aspx() {
            return new ASP.pages_ep_ep301030_aspx();
        }
        
        static object Create_ASP_pages_ep_ep307000_aspx() {
            return new ASP.pages_ep_ep307000_aspx();
        }
        
        static object Create_ASP_pages_ep_ep305000_aspx() {
            return new ASP.pages_ep_ep305000_aspx();
        }
    }
}
