//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_q13m5rso {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_q13m5rso() {
        }
        
        static object Create_ASP_pages_gl_gl403000_aspx() {
            return new ASP.pages_gl_gl403000_aspx();
        }
        
        static object Create_ASP_pages_gl_gl103040_aspx() {
            return new ASP.pages_gl_gl103040_aspx();
        }
        
        static object Create_ASP_pages_gl_gl101000_aspx() {
            return new ASP.pages_gl_gl101000_aspx();
        }
        
        static object Create_ASP_pages_gl_gl204500_aspx() {
            return new ASP.pages_gl_gl204500_aspx();
        }
        
        static object Create_ASP_pages_gl_gl203500_aspx() {
            return new ASP.pages_gl_gl203500_aspx();
        }
        
        static object Create_ASP_pages_gl_gl506000_aspx() {
            return new ASP.pages_gl_gl506000_aspx();
        }
    }
}
