//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_v5nk4ur0 {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_v5nk4ur0() {
        }
        
        static object Create_ASP_pages_pm_pm209900_aspx() {
            return new ASP.pages_pm_pm209900_aspx();
        }
        
        static object Create_ASP_pages_pm_pm202000_aspx() {
            return new ASP.pages_pm_pm202000_aspx();
        }
        
        static object Create_ASP_pages_pm_pm503000_aspx() {
            return new ASP.pages_pm_pm503000_aspx();
        }
        
        static object Create_ASP_pages_pm_pm209500_aspx() {
            return new ASP.pages_pm_pm209500_aspx();
        }
        
        static object Create_ASP_pages_pm_pm302000_aspx() {
            return new ASP.pages_pm_pm302000_aspx();
        }
        
        static object Create_ASP_pages_pm_pm208030_aspx() {
            return new ASP.pages_pm_pm208030_aspx();
        }
    }
}
