//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_5lnhe5ih {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_5lnhe5ih() {
        }
        
        static object Create_ASP_pages_gl_gl505510_aspx() {
            return new ASP.pages_gl_gl505510_aspx();
        }
        
        static object Create_ASP_pages_gl_gl501000_aspx() {
            return new ASP.pages_gl_gl501000_aspx();
        }
        
        static object Create_ASP_pages_gl_gl202500_aspx() {
            return new ASP.pages_gl_gl202500_aspx();
        }
        
        static object Create_ASP_pages_gl_gl104030_aspx() {
            return new ASP.pages_gl_gl104030_aspx();
        }
        
        static object Create_ASP_pages_gl_gl103060_aspx() {
            return new ASP.pages_gl_gl103060_aspx();
        }
        
        static object Create_ASP_pages_gl_gl107500_aspx() {
            return new ASP.pages_gl_gl107500_aspx();
        }
        
        static object Create_ASP_pages_gl_gl104020_aspx() {
            return new ASP.pages_gl_gl104020_aspx();
        }
        
        static object Create_ASP_pages_gl_gl302010_aspx() {
            return new ASP.pages_gl_gl302010_aspx();
        }
    }
}
