//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_1b3drelo {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_1b3drelo() {
        }
        
        static object Create_ASP_pages_cr_cr306020_aspx() {
            return new ASP.pages_cr_cr306020_aspx();
        }
        
        static object Create_ASP_pages_cr_co409030_aspx() {
            return new ASP.pages_cr_co409030_aspx();
        }
        
        static object Create_ASP_pages_cr_cr305010_aspx() {
            return new ASP.pages_cr_cr305010_aspx();
        }
        
        static object Create_ASP_pages_cr_cr306015_aspx() {
            return new ASP.pages_cr_cr306015_aspx();
        }
        
        static object Create_ASP_pages_cr_cr503420_aspx() {
            return new ASP.pages_cr_cr503420_aspx();
        }
        
        static object Create_ASP_pages_cr_cr307000_aspx() {
            return new ASP.pages_cr_cr307000_aspx();
        }
        
        static object Create_ASP_pages_cr_cr102000_aspx() {
            return new ASP.pages_cr_cr102000_aspx();
        }
        
        static object Create_ASP_pages_cr_cr503400_aspx() {
            return new ASP.pages_cr_cr503400_aspx();
        }
    }
}
