//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_qh1abhci {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_qh1abhci() {
        }
        
        static object Create_ASP_pages_ep_ep407000_aspx() {
            return new ASP.pages_ep_ep407000_aspx();
        }
        
        static object Create_ASP_pages_ep_ep205500_aspx() {
            return new ASP.pages_ep_ep205500_aspx();
        }
        
        static object Create_ASP_pages_ep_ep102000_aspx() {
            return new ASP.pages_ep_ep102000_aspx();
        }
        
        static object Create_ASP_pages_ep_ep404100_aspx() {
            return new ASP.pages_ep_ep404100_aspx();
        }
        
        static object Create_ASP_pages_ep_ep205010_aspx() {
            return new ASP.pages_ep_ep205010_aspx();
        }
        
        static object Create_ASP_pages_ep_ep503500_aspx() {
            return new ASP.pages_ep_ep503500_aspx();
        }
        
        static object Create_ASP_pages_ep_ep507020_aspx() {
            return new ASP.pages_ep_ep507020_aspx();
        }
        
        static object Create_ASP_pages_ep_ep301010_aspx() {
            return new ASP.pages_ep_ep301010_aspx();
        }
        
        static object Create_ASP_pages_ep_ep202000_aspx() {
            return new ASP.pages_ep_ep202000_aspx();
        }
        
        static object Create_ASP_pages_ep_ep303010_aspx() {
            return new ASP.pages_ep_ep303010_aspx();
        }
        
        static object Create_ASP_pages_ep_ep305100_aspx() {
            return new ASP.pages_ep_ep305100_aspx();
        }
    }
}
