//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_5vbjun5l {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_5vbjun5l() {
        }
        
        static object Create_ASP_pages_sm_sm302010_aspx() {
            return new ASP.pages_sm_sm302010_aspx();
        }
        
        static object Create_ASP_pages_sm_sm205010_aspx() {
            return new ASP.pages_sm_sm205010_aspx();
        }
        
        static object Create_ASP_pages_sm_sm205060_aspx() {
            return new ASP.pages_sm_sm205060_aspx();
        }
        
        static object Create_ASP_pages_sm_sm206026_aspx() {
            return new ASP.pages_sm_sm206026_aspx();
        }
        
        static object Create_ASP_pages_sm_sm201510_aspx() {
            return new ASP.pages_sm_sm201510_aspx();
        }
        
        static object Create_ASP_pages_sm_sm206530_aspx() {
            return new ASP.pages_sm_sm206530_aspx();
        }
        
        static object Create_ASP_pages_sm_sm202520_aspx() {
            return new ASP.pages_sm_sm202520_aspx();
        }
    }
}
