//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_jxkqtkwl {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_jxkqtkwl() {
        }
        
        static object Create_ASP_pages_sm_sm203520_aspx() {
            return new ASP.pages_sm_sm203520_aspx();
        }
        
        static object Create_ASP_pages_sm_sm200524_aspx() {
            return new ASP.pages_sm_sm200524_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204540_aspx() {
            return new ASP.pages_sm_sm204540_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204004_aspx() {
            return new ASP.pages_sm_sm204004_aspx();
        }
        
        static object Create_ASP_pages_sm_sm200529_aspx() {
            return new ASP.pages_sm_sm200529_aspx();
        }
        
        static object Create_ASP_pages_sm_sm205520_aspx() {
            return new ASP.pages_sm_sm205520_aspx();
        }
        
        static object Create_ASP_pages_sm_sm201005_aspx() {
            return new ASP.pages_sm_sm201005_aspx();
        }
        
        static object Create_ASP_pages_sm_sm303010_aspx() {
            return new ASP.pages_sm_sm303010_aspx();
        }
        
        static object Create_ASP_pages_sm_sm205070_aspx() {
            return new ASP.pages_sm_sm205070_aspx();
        }
    }
}
