#pragma checksum "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "F3ACCB2B8A0058C115ED0CB3EC84BD63CC542FC2"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Page_WZ201000 : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    protected global::PX.Web.UI.PXDataSource ds;
    
    #line default
    #line hidden
    
    
    #line 49 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    protected global::PX.Web.UI.PXLayoutRule PXLayoutRule1;
    
    #line default
    #line hidden
    
    
    #line 50 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    protected global::PX.Web.UI.PXTextEdit edName;
    
    #line default
    #line hidden
    
    
    #line 51 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    protected global::PX.Web.UI.PXDropDown edStatus;
    
    #line default
    #line hidden
    
    
    #line 52 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    protected global::PX.Web.UI.PXTextEdit edExecutionDate;
    
    #line default
    #line hidden
    
    
    #line 53 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    protected global::PX.Web.UI.PXSelector edRolename;
    
    #line default
    #line hidden
    
    
    #line 55 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    protected global::PX.Web.UI.PXSelector edWorkspaceID;
    
    #line default
    #line hidden
    
    
    #line 56 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    protected global::PX.Web.UI.PXSelector edSubcategoryID;
    
    #line default
    #line hidden
    
    
    #line 57 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    protected global::PX.Web.UI.PXTextEdit edOrder;
    
    #line default
    #line hidden
    
    
    #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    protected global::PX.Web.UI.PXGrid grid;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
    
    public new ASP.masterpages_listview_master Master {
        get {
            return ((ASP.masterpages_listview_master)(base.Master));
        }
    }
}
namespace ASP {
    
    #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 5 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    using System.Web.UI.DataVisualization.Charting;
    
    #line default
    #line hidden
    
    #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
    using PX.Web.UI;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class pages_wz_wz201000_aspx : global::Page_WZ201000, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.pages_wz_wz201000_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public pages_wz_wz201000_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Pages/WZ/WZ201000.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.pages_wz_wz201000_aspx.@__initialized == false)) {
                dependencies = new string[6];
                dependencies[0] = "~/Pages/WZ/WZ201000.aspx";
                dependencies[1] = "~/Controls/PageTitle.ascx";
                dependencies[2] = "~/Controls/PageTitle.ascx.cs";
                dependencies[3] = "~/MasterPages/ListView.master";
                dependencies[4] = "~/MasterPages/ListView.master.cs";
                dependencies[5] = "~/Pages/WZ/WZ201000.aspx.cs";
                global::ASP.pages_wz_wz201000_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.pages_wz_wz201000_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
	<script language=""javascript"" type=""text/javascript"">
		function commandResult(ds, context)
		{
			if (context.command == ""Save"" || context.command == ""Delete"")
			{
				var ds = px_all[context.id];
				var isSitemapAltered = (ds.callbackResultArg == ""RefreshSitemap"");
				if (isSitemapAltered) __refreshMainMenu();
			}
		}
	</script>
	");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        340,
                        352,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.pages_wz_wz201000_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.pages_wz_wz201000_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control3(PX.Web.UI.PXDataSourceEvents @__ctrl) {
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.CommandPerformed = "commandResult";
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDSCallbackCommand @__BuildControl__control5() {
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl;
            
            #line 21 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXDSCallbackCommand();
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Name = "Save";
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.CommitChanges = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDSCallbackCommand @__BuildControl__control6() {
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl;
            
            #line 22 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXDSCallbackCommand();
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Name = "Insert";
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.CommitChanges = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDSCallbackCommand @__BuildControl__control7() {
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl;
            
            #line 23 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXDSCallbackCommand();
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Name = "Delete";
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.CommitChanges = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDSCallbackCommand @__BuildControl__control8() {
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl;
            
            #line 24 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXDSCallbackCommand();
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Name = "Next";
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.CommitChanges = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDSCallbackCommand @__BuildControl__control9() {
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl;
            
            #line 25 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXDSCallbackCommand();
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Name = "Previous";
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.CommitChanges = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDSCallbackCommand @__BuildControl__control10() {
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl;
            
            #line 26 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXDSCallbackCommand();
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Name = "Last";
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.CommitChanges = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDSCallbackCommand @__BuildControl__control11() {
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl;
            
            #line 27 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXDSCallbackCommand();
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Name = "First";
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.CommitChanges = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDSCallbackCommand @__BuildControl__control12() {
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl;
            
            #line 28 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXDSCallbackCommand();
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Name = "ViewScenarioDetails";
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DependOnGrid = "grid";
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.CommitChanges = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDSCallbackCommand @__BuildControl__control13() {
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl;
            
            #line 29 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXDSCallbackCommand();
            
            #line default
            #line hidden
            
            #line 29 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Name = "Cancel";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control4(PX.Web.UI.PXDSCallbackCollection @__ctrl) {
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl1;
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl1 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl2;
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl2 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl3;
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl3 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl4;
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl4 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl5;
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl5 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl6;
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl6 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl7;
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl7 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl8;
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl8 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl8);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDSCallbackCommand @__ctrl9;
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl9 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl9);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDataSource @__BuildControlds() {
            global::PX.Web.UI.PXDataSource @__ctrl;
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXDataSource();
            
            #line default
            #line hidden
            this.ds = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.ID = "ds";
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.PrimaryView = "Scenarios";
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.TypeName = "PX.Objects.WZ.WZScenarioEntry";
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Visible = true;
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            this.@__BuildControl__control3(@__ctrl.ClientEvents);
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            this.@__BuildControl__control4(@__ctrl.CallbackCommands);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        692,
                        1031,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1723,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlcont1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDataSource @__ctrl2;
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl2 = this.@__BuildControlds();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl3 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\t");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1807,
                        3,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control19() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2965,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXLayoutRule @__BuildControlPXLayoutRule1() {
            global::PX.Web.UI.PXLayoutRule @__ctrl;
            
            #line 49 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXLayoutRule();
            
            #line default
            #line hidden
            this.PXLayoutRule1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 49 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.ID = "PXLayoutRule1";
            
            #line default
            #line hidden
            
            #line 49 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.StartColumn = true;
            
            #line default
            #line hidden
            
            #line 49 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.LabelsWidth = "SM";
            
            #line default
            #line hidden
            
            #line 49 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.ControlSize = "M";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2987,
                        105,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control20() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3092,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXTextEdit @__BuildControledName() {
            global::PX.Web.UI.PXTextEdit @__ctrl;
            
            #line 50 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXTextEdit();
            
            #line default
            #line hidden
            this.edName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 50 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.ID = "edName";
            
            #line default
            #line hidden
            
            #line 50 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "Name";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3114,
                        61,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control21() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3175,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDropDown @__BuildControledStatus() {
            global::PX.Web.UI.PXDropDown @__ctrl;
            
            #line 51 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXDropDown();
            
            #line default
            #line hidden
            this.edStatus = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 51 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.ID = "edStatus";
            
            #line default
            #line hidden
            
            #line 51 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "Status";
            
            #line default
            #line hidden
            
            #line 51 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Enabled = false;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3197,
                        80,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control22() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3277,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXTextEdit @__BuildControledExecutionDate() {
            global::PX.Web.UI.PXTextEdit @__ctrl;
            
            #line 52 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXTextEdit();
            
            #line default
            #line hidden
            this.edExecutionDate = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 52 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.ID = "edExecutionDate";
            
            #line default
            #line hidden
            
            #line 52 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "ExecutionDate";
            
            #line default
            #line hidden
            
            #line 52 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Enabled = false;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3299,
                        94,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control23() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3393,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXSelector @__BuildControledRolename() {
            global::PX.Web.UI.PXSelector @__ctrl;
            
            #line 53 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXSelector();
            
            #line default
            #line hidden
            this.edRolename = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 53 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.ID = "edRolename";
            
            #line default
            #line hidden
            
            #line 53 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "Rolename";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3415,
                        68,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control24() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    \r\n\t\t            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3483,
                        38,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXSelector @__BuildControledWorkspaceID() {
            global::PX.Web.UI.PXSelector @__ctrl;
            
            #line 55 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXSelector();
            
            #line default
            #line hidden
            this.edWorkspaceID = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 55 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "WorkspaceID";
            
            #line default
            #line hidden
            
            #line 55 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.ID = "edWorkspaceID";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3521,
                        75,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control25() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\t\t            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3596,
                        16,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXSelector @__BuildControledSubcategoryID() {
            global::PX.Web.UI.PXSelector @__ctrl;
            
            #line 56 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXSelector();
            
            #line default
            #line hidden
            this.edSubcategoryID = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 56 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "SubcategoryID";
            
            #line default
            #line hidden
            
            #line 56 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.ID = "edSubcategoryID";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3612,
                        79,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control26() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3691,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXTextEdit @__BuildControledOrder() {
            global::PX.Web.UI.PXTextEdit @__ctrl;
            
            #line 57 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXTextEdit();
            
            #line default
            #line hidden
            this.edOrder = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 57 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.ID = "edOrder";
            
            #line default
            #line hidden
            
            #line 57 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "Order";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3713,
                        63,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control27() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3776,
                        18,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control18(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl1 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXLayoutRule @__ctrl2;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl2 = this.@__BuildControlPXLayoutRule1();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl3 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXTextEdit @__ctrl4;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl4 = this.@__BuildControledName();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl5 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDropDown @__ctrl6;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl6 = this.@__BuildControledStatus();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl7 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXTextEdit @__ctrl8;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl8 = this.@__BuildControledExecutionDate();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl9 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXSelector @__ctrl10;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl10 = this.@__BuildControledRolename();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl11 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXSelector @__ctrl12;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl12 = this.@__BuildControledWorkspaceID();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl13 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXSelector @__ctrl14;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl14 = this.@__BuildControledSubcategoryID();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl15 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXTextEdit @__ctrl16;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl16 = this.@__BuildControledOrder();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl17;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl17 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control29() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 39 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 39 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "Name";
            
            #line default
            #line hidden
            
            #line 39 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(300D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 39 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.CommitChanges = true;
            
            #line default
            #line hidden
            
            #line 39 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.LinkCommand = "ViewScenarioDetails";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control30() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 40 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 40 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "Status";
            
            #line default
            #line hidden
            
            #line 40 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control31() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 41 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 41 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "ExecutionDate";
            
            #line default
            #line hidden
            
            #line 41 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control32() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 42 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 42 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "ExecutionPeriodID";
            
            #line default
            #line hidden
            
            #line 42 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control33() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 43 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 43 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "Rolename";
            
            #line default
            #line hidden
            
            #line 43 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control34() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 44 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "WorkspaceID";
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Label = "Workspace";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control35() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 45 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 45 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "SubcategoryID";
            
            #line default
            #line hidden
            
            #line 45 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 45 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Label = "Category";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control36() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 46 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 46 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataField = "ScenarioOrder";
            
            #line default
            #line hidden
            
            #line 46 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 46 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.AllowShowHide = global::PX.Web.UI.AllowShowHide.True;
            
            #line default
            #line hidden
            
            #line 46 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 46 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.SyncVisible = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control28(PX.Web.UI.PXGridColumnCollection @__ctrl) {
            global::PX.Web.UI.PXGridColumn @__ctrl1;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl1 = this.@__BuildControl__control29();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl2;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl2 = this.@__BuildControl__control30();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl3;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl3 = this.@__BuildControl__control31();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl4;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl4 = this.@__BuildControl__control32();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl5;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl5 = this.@__BuildControl__control33();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl6;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl6 = this.@__BuildControl__control34();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl7;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl7 = this.@__BuildControl__control35();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl8;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl8 = this.@__BuildControl__control36();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl8);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridLevel @__BuildControl__control17() {
            global::PX.Web.UI.PXGridLevel @__ctrl;
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridLevel();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.RowTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control18));
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataMember = "Scenarios";
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            this.@__BuildControl__control28(@__ctrl.Columns);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control16(PX.Web.UI.PXGridLevelCollection @__ctrl) {
            global::PX.Web.UI.PXGridLevel @__ctrl1;
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl1 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control37(PX.Web.UI.PXAutoSizeInfo @__ctrl) {
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Container = global::PX.Web.UI.DockContainer.Window;
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Enabled = true;
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.MinHeight = 200;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGrid @__BuildControlgrid() {
            global::PX.Web.UI.PXGrid @__ctrl;
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl = new global::PX.Web.UI.PXGrid();
            
            #line default
            #line hidden
            this.grid = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "Primary";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.ID = "grid";
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(400D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.AllowPaging = true;
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.AllowSearch = true;
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.AdjustPageSize = global::PX.Web.UI.GridPageSizeMode.Auto;
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataSourceID = "ds";
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.SyncPosition = true;
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.AutoAdjustColumns = true;
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            this.@__BuildControl__control16(@__ctrl.Levels);
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            this.@__BuildControl__control37(@__ctrl.AutoSize);
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.DataBound += new System.EventHandler(this.grid_OnDataBound);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1810,
                        2115,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control38() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3925,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlcont2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 33 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl1 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 33 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGrid @__ctrl2;
            
            #line 33 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl2 = this.@__BuildControlgrid();
            
            #line default
            #line hidden
            
            #line 33 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 33 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl3 = this.@__BuildControl__control38();
            
            #line default
            #line hidden
            
            #line 33 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(pages_wz_wz201000_aspx @__ctrl) {
            
            #line 1 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.MasterPageFile = "~/MasterPages/ListView.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__ctrl.Title = "Untitled Page";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            this.AddContentTemplate("phDS", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlcont1)));
            
            #line default
            #line hidden
            
            #line 33 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            this.AddContentTemplate("phL", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlcont2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Users\Josh\Documents\AcumaticaLearning\PhoneRepairShop\Pages\WZ\WZ201000.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            this.StyleSheetTheme = "Default";
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.pages_wz_wz201000_aspx.@__fileDependencies);
            this.ValidateRequestMode = System.Web.UI.ValidateRequestMode.Disabled;
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -382470977;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
