//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_lbu4hvje {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_lbu4hvje() {
        }
        
        static object Create_ASP_pages_sm_sm200505_aspx() {
            return new ASP.pages_sm_sm200505_aspx();
        }
        
        static object Create_ASP_pages_sm_sm201530_aspx() {
            return new ASP.pages_sm_sm201530_aspx();
        }
        
        static object Create_ASP_pages_sm_sm202540_aspx() {
            return new ASP.pages_sm_sm202540_aspx();
        }
        
        static object Create_ASP_pages_sm_sm302000_aspx() {
            return new ASP.pages_sm_sm302000_aspx();
        }
        
        static object Create_ASP_pages_sm_sm200520_aspx() {
            return new ASP.pages_sm_sm200520_aspx();
        }
        
        static object Create_ASP_pages_sm_sm201065_aspx() {
            return new ASP.pages_sm_sm201065_aspx();
        }
        
        static object Create_ASP_pages_sm_sm206540_aspx() {
            return new ASP.pages_sm_sm206540_aspx();
        }
        
        static object Create_ASP_pages_sm_sm200521_aspx() {
            return new ASP.pages_sm_sm200521_aspx();
        }
        
        static object Create_ASP_pages_sm_sm401000_aspx() {
            return new ASP.pages_sm_sm401000_aspx();
        }
    }
}
