//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_hrqv2thq {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_hrqv2thq() {
        }
        
        static object Create_ASP_pages_in_in405000_aspx() {
            return new ASP.pages_in_in405000_aspx();
        }
        
        static object Create_ASP_pages_in_in505000_aspx() {
            return new ASP.pages_in_in505000_aspx();
        }
        
        static object Create_ASP_pages_in_in301020_aspx() {
            return new ASP.pages_in_in301020_aspx();
        }
        
        static object Create_ASP_pages_in_in509500_aspx() {
            return new ASP.pages_in_in509500_aspx();
        }
        
        static object Create_ASP_pages_in_in208500_aspx() {
            return new ASP.pages_in_in208500_aspx();
        }
        
        static object Create_ASP_pages_in_in408000_aspx() {
            return new ASP.pages_in_in408000_aspx();
        }
        
        static object Create_ASP_pages_in_in402000_aspx() {
            return new ASP.pages_in_in402000_aspx();
        }
    }
}
