//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_o3znr3n4 {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_o3znr3n4() {
        }
        
        static object Create_ASP_pages_cs_cs100000_aspx() {
            return new ASP.pages_cs_cs100000_aspx();
        }
        
        static object Create_ASP_pages_cs_cs206500_aspx() {
            return new ASP.pages_cs_cs206500_aspx();
        }
        
        static object Create_ASP_pages_cs_cs205010_aspx() {
            return new ASP.pages_cs_cs205010_aspx();
        }
        
        static object Create_ASP_pages_cs_cs209010_aspx() {
            return new ASP.pages_cs_cs209010_aspx();
        }
        
        static object Create_ASP_pages_cs_cs202000_aspx() {
            return new ASP.pages_cs_cs202000_aspx();
        }
        
        static object Create_ASP_pages_cs_cs206000_aspx() {
            return new ASP.pages_cs_cs206000_aspx();
        }
        
        static object Create_ASP_pages_cs_cs207500_aspx() {
            return new ASP.pages_cs_cs207500_aspx();
        }
        
        static object Create_ASP_pages_cs_cs206020_aspx() {
            return new ASP.pages_cs_cs206020_aspx();
        }
    }
}
