//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_334bkiia {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_334bkiia() {
        }
        
        static object Create_ASP_pages_ar_ar405000_aspx() {
            return new ASP.pages_ar_ar405000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar406000_aspx() {
            return new ASP.pages_ar_ar406000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar510000_aspx() {
            return new ASP.pages_ar_ar510000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar509900_aspx() {
            return new ASP.pages_ar_ar509900_aspx();
        }
        
        static object Create_ASP_pages_ar_ar506000_aspx() {
            return new ASP.pages_ar_ar506000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar208000_aspx() {
            return new ASP.pages_ar_ar208000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar404300_aspx() {
            return new ASP.pages_ar_ar404300_aspx();
        }
        
        static object Create_ASP_pages_ar_ar503000_aspx() {
            return new ASP.pages_ar_ar503000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar207000_aspx() {
            return new ASP.pages_ar_ar207000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar504000_aspx() {
            return new ASP.pages_ar_ar504000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar407000_aspx() {
            return new ASP.pages_ar_ar407000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar102000_aspx() {
            return new ASP.pages_ar_ar102000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar303000_aspx() {
            return new ASP.pages_ar_ar303000_aspx();
        }
    }
}
