//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_0fczbajb {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_0fczbajb() {
        }
        
        static object Create_ASP_pages_cr_co409080_aspx() {
            return new ASP.pages_cr_co409080_aspx();
        }
        
        static object Create_ASP_pages_cr_co409070_aspx() {
            return new ASP.pages_cr_co409070_aspx();
        }
        
        static object Create_ASP_pages_cr_co409010_aspx() {
            return new ASP.pages_cr_co409010_aspx();
        }
        
        static object Create_ASP_pages_cr_cr505020_aspx() {
            return new ASP.pages_cr_cr505020_aspx();
        }
        
        static object Create_ASP_pages_cr_cr503011_aspx() {
            return new ASP.pages_cr_cr503011_aspx();
        }
        
        static object Create_ASP_pages_cr_cr503220_aspx() {
            return new ASP.pages_cr_cr503220_aspx();
        }
        
        static object Create_ASP_pages_cr_cr101000_aspx() {
            return new ASP.pages_cr_cr101000_aspx();
        }
        
        static object Create_ASP_pages_cr_co409063_aspx() {
            return new ASP.pages_cr_co409063_aspx();
        }
        
        static object Create_ASP_pages_cr_cr204000_aspx() {
            return new ASP.pages_cr_cr204000_aspx();
        }
    }
}
