//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_04qrz10w {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_04qrz10w() {
        }
        
        static object Create_ASP_pages_fs_fs206000_aspx() {
            return new ASP.pages_fs_fs206000_aspx();
        }
        
        static object Create_ASP_pages_fs_fs203600_aspx() {
            return new ASP.pages_fs_fs203600_aspx();
        }
        
        static object Create_ASP_pages_fs_fs304010_aspx() {
            return new ASP.pages_fs_fs304010_aspx();
        }
        
        static object Create_ASP_pages_fs_fs201200_aspx() {
            return new ASP.pages_fs_fs201200_aspx();
        }
        
        static object Create_ASP_pages_fs_fs500700_aspx() {
            return new ASP.pages_fs_fs500700_aspx();
        }
        
        static object Create_ASP_pages_fs_fs500202_aspx() {
            return new ASP.pages_fs_fs500202_aspx();
        }
        
        static object Create_ASP_pages_fs_fs300250_aspx() {
            return new ASP.pages_fs_fs300250_aspx();
        }
        
        static object Create_ASP_pages_fs_fs500100_aspx() {
            return new ASP.pages_fs_fs500100_aspx();
        }
    }
}
