//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_35mahmid {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_35mahmid() {
        }
        
        static object Create_ASP_pages_sm_sm208020_aspx() {
            return new ASP.pages_sm_sm208020_aspx();
        }
        
        static object Create_ASP_pages_sm_sm202550_aspx() {
            return new ASP.pages_sm_sm202550_aspx();
        }
        
        static object Create_ASP_pages_sm_sm211500_aspx() {
            return new ASP.pages_sm_sm211500_aspx();
        }
        
        static object Create_ASP_pages_sm_sm201040_aspx() {
            return new ASP.pages_sm_sm201040_aspx();
        }
        
        static object Create_ASP_pages_sm_sm202530_aspx() {
            return new ASP.pages_sm_sm202530_aspx();
        }
        
        static object Create_ASP_pages_sm_sm201035_aspx() {
            return new ASP.pages_sm_sm201035_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204570_aspx() {
            return new ASP.pages_sm_sm204570_aspx();
        }
        
        static object Create_ASP_pages_sm_sm203030_aspx() {
            return new ASP.pages_sm_sm203030_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204010_aspx() {
            return new ASP.pages_sm_sm204010_aspx();
        }
    }
}
